name: deploy-api
on:
  push:
    paths:
      - "api/**"
      - "!api/README.md"
      - "!eb/build_and_push_image.sh"
  workflow_dispatch:
jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}
      - name: Get repository source code
        uses: actions/checkout@v2
      - run: |
          cd api
          mkdir -p config
          aws ecr get-login-password --region ${{secrets.AWS_DEV_REGION}} > config/docker_login
          bash -e eb/build_and_push_image.sh ${{github.sha}} ${{secrets.AWS_ECR_REPO_URL}}
      - name: Deploy image to EB instance
        uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: 'deploy dev'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEV_REGION }}