name: deploy-api
on:
  push:
    paths:
      - "api/**"
      - "!api/README.md"
      - "!eb/build_and_push_image.sh"
  workflow_dispatch:
jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}
      - name: Get repository source code
        uses: actions/checkout@v2
      - run: |
          cd api
          zip -r deploy.zip . -x '*.git*'
          npm install -g beanstalk-deploy
          beanstalk-deploy helio-e-commerce-api Helioecommerceapi-env 1 us-east-2 deploy.zip
