name: deploy-api
on:
  push:
    paths:
      - "api/**"
      - "!api/README.md"
      - "!eb/build_and_push_image.sh"
  workflow_dispatch:
jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository source code
        uses: actions/checkout@v2

      - name: Generate deployment package
        run: |
          cd api
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: helio-e-commerce-api
          environment_name: Helioecommerceapi-env
          version_label: ${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: api/deploy.zip
