name: deploy-api
on:
  push:
    paths:
      - "api/**"
      - "!api/README.md"
      - "!eb/build_and_push_image.sh"
  workflow_dispatch:
jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository source code
        uses: actions/checkout@v2
      - run: |
          pwd
          ls
          cd api
          pwd
          ls
          echo "Zipping..."
          zip -r deploy.zip . -x '*.git*'
          pwd
          ls
          echo "Installing beantalk-deploy..."
          npm install -g beanstalk-deploy
          echo "Running beanstalk-deploy..."
          beanstalk-deploy