name: deploy-api
on:
  push:
    paths:
      - "api/**"
      - "!api/README.md"
  workflow_dispatch:
jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}
      # - run: pwd
      # - run: ls -a
      # - run: cd ~
      # - run: pwd
      # - run: ls -a
      # - run: mkdir -p .aws
      - run: mkdir -p config
      # - run: printf "[eb-cli]\naws_access_key_id = %s\naws_secret_access_key = %s\n" "${{secrets.AWS_ACCESS_KEY_ID}}" "${{secrets.AWS_SECRET_ACCESS_KEY}}" > .aws/aws_credentials
      # - run: printf "[profile eb-cli]\nregion=${{secrets.AWS_DEV_REGION}}\noutput=json" > .aws/aws_config
      - run: aws ecr get-login-password --region ${{secrets.AWS_DEV_REGION}} > config/docker_login
      - run: ls
      - run: cd config
      - run: ls
  