name: deploy-api
on:
  push:
    paths:
      - "api/**"
      - "!api/README.md"
  workflow_dispatch:
jobs:
  configure-aws:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
          ls
          cd ..
          pwd
          ls
          cd ..
          pwd
          ls
          cd ..
          pwd
          ls
          cd ..
          pwd
          ls
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEV_REGION }}
      - run: |
          mkdir -p config
          ls
          aws ecr get-login-password --region ${{secrets.AWS_DEV_REGION}} > config/docker_login
          cd config
          pwd
          ls
  